version: "3.8"
volumes:
  pgdata: {}
services:
  db:
    build:
      context: .
      dockerfile: ./docker/local/db/Dockerfile
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=temba
      - POSTGRES_PASSWORD=temba
      - POSTGRES_DB=temba
  redis:
    image: redis:alpine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - bootstrap.memory_lock=true
      - ES_HEAP_SIZE=512m
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
  rapidpro:
    build:
      context: .
      dockerfile: ./docker/local/rapidpro/Dockerfile
    command: /start
    volumes:
      - ./src/rapidpro:/app
      - ./src/rapidpro-apps/weni:/app/weni
      - ./src/push-branding/push:/app/static/brands/push
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      - POSTGRES_DB=temba
      - POSTGRES_USER=temba
      - POSTGRES_PASSWORD=temba
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=10
      - MAILROOM_URL=http://mailroom:8090
      - DATABASE_URL=postgis://temba:temba@db:5432/temba
      - DATABASE_USE_SSL=false
      - WENI_DOMAIN=lvh.me
      - OIDC_OP_AUTHORIZATION_ENDPOINT=https://accounts.weni.ai/auth/realms/weni-develop/protocol/openid-connect/auth
      - OIDC_OP_JWKS_ENDPOINT=https://accounts.weni.ai/auth/realms/weni-develop/protocol/openid-connect/certs
      - OIDC_OP_TOKEN_ENDPOINT=https://accounts.weni.ai/auth/realms/weni-develop/protocol/openid-connect/token
      - OIDC_OP_USER_ENDPOINT=https://accounts.weni.ai/auth/realms/weni-develop/protocol/openid-connect/userinfo
      - OIDC_RP_CLIENT_ID=push-backend
      - OIDC_RP_CLIENT_SECRET=4d124446-99a0-4105-945d-6b32c3c7dcb5
      - OIDC_RP_SIGN_ALGO=RS256
      - OIDC_SERVER_URL=https://accounts.weni.ai
      - ANNOUNCEMENT_LEFT=O Push agora é Weni Fluxos
      - ANNOUNCEMENT_RIGHT=Novo módulo que estará disponível na nossa plataforma unificada em breve.
      - ANNOUNCEMENT_LINK=https://weni.ai/blog/modularizacao-plataformas/
      - ANNOUNCEMENT_BUTTON=Saiba mais
      - HOTJAR_ID=2221595
      - SECRET_KEY_CHECK_LEGACY_USER=123
  grpc:
    build:
      context: .
      dockerfile: ./docker/local/rapidpro/Dockerfile
    command: python manage.py grpcrunserver --dev
    volumes:
      - ./src/rapidpro:/app
      - ./src/rapidpro-apps/weni:/app/weni
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      - POSTGRES_DB=temba
      - POSTGRES_USER=temba
      - POSTGRES_PASSWORD=temba
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=10
      - MAILROOM_URL=http://mailroom:8090
      - DATABASE_URL=postgis://temba:temba@db:5432/temba
    ports:
      - "50051:50051"
  nginx:
    build:
      context: .
      dockerfile: ./docker/local/nginx/Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - rapidpro
      - mailroom
      - courier
  mailroom:
    build:
      context: .
      dockerfile: docker/local/mailroom/Dockerfile
    depends_on:
      - rapidpro
    environment:
      - MAILROOM_ADDRESS=0.0.0.0
      - MAILROOM_DB=postgres://temba:temba@db/temba?sslmode=disable
      - MAILROOM_REDIS=redis://redis:6379/15
      - MAILROOM_ELASTIC=http://elasticsearch:9200
      - MAILROOM_DOMAIN=rapidpro
      - MAILROOM_ATTACHMENT_DOMAIN=rapidpro
  courier:
    build:
      context: .
      dockerfile: docker/local/courier/Dockerfile
    depends_on:
      - rapidpro
    environment:
      - COURIER_DOMAIN=localhost
      - COURIER_DB=postgres://temba:temba@db/temba
      - COURIER_REDIS=redis://redis:6379/13
  indexer:
    build:
      context: .
      dockerfile: docker/local/indexer/Dockerfile
    depends_on:
      - rapidpro
    environment:
      - INDEXER_DB=postgres://temba:temba@db/temba?sslmode=disable
      - INDEXER_ELASTIC_URL=http://elasticsearch:9200
