version: "3.8"
volumes:
  pgdata: {}
services:
  db:
    build:
      context: .
      dockerfile: ./docker/local/db/Dockerfile
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=temba
      - POSTGRES_PASSWORD=temba
      - POSTGRES_DB=temba
  redis:
    image: redis:alpine
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    environment:
      - bootstrap.memory_lock=true
      - ES_HEAP_SIZE=512m
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - discovery.type=single-node
  rapidpro:
    build:
      context: .
      dockerfile: ./docker/local/rapidpro/Dockerfile
    command: /start
    volumes:
      - ./src/rapidpro:/app
      - ./src/rapidpro-apps/weni:/app/weni
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      - POSTGRES_DB=temba
      - POSTGRES_USER=temba
      - POSTGRES_PASSWORD=temba
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=10
      - MAILROOM_URL=http://mailroom:8090
      - DATABASE_URL=postgis://temba:temba@db:5432/temba
  grpc:
    build:
      context: .
      dockerfile: ./docker/local/rapidpro/Dockerfile
    command: python manage.py grpcrunserver --dev
    volumes:
      - ./src/rapidpro:/app
      - ./src/rapidpro-apps/weni:/app/weni
    depends_on:
      - db
      - redis
      - elasticsearch
    environment:
      - POSTGRES_DB=temba
      - POSTGRES_USER=temba
      - POSTGRES_PASSWORD=temba
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=10
      - MAILROOM_URL=http://mailroom:8090
      - DATABASE_URL=postgis://temba:temba@db:5432/temba
    ports:
      - "50051:50051"
  nginx:
    build:
      context: .
      dockerfile: ./docker/local/nginx/Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - rapidpro
      - mailroom
      - courier
  mailroom:
    build:
      context: .
      dockerfile: docker/local/mailroom/Dockerfile
    depends_on:
      - rapidpro
    environment:
      - MAILROOM_ADDRESS=0.0.0.0
      - MAILROOM_DB=postgres://temba:temba@db/temba?sslmode=disable
      - MAILROOM_REDIS=redis://redis:6379/15
      - MAILROOM_ELASTIC=http://elasticsearch:9200
      - MAILROOM_DOMAIN=rapidpro
      - MAILROOM_ATTACHMENT_DOMAIN=rapidpro
  courier:
    build:
      context: .
      dockerfile: docker/local/courier/Dockerfile
    depends_on:
      - rapidpro
    environment:
      - COURIER_DOMAIN=localhost
      - COURIER_DB=postgres://temba:temba@db/temba
      - COURIER_REDIS=redis://redis:6379/13
  indexer:
    build:
      context: .
      dockerfile: docker/local/indexer/Dockerfile
    depends_on:
      - rapidpro
    environment:
      - INDEXER_DB=postgres://temba:temba@db/temba?sslmode=disable
      - INDEXER_ELASTIC_URL=http://elasticsearch:9200
