#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py collectstatic --no-input
python manage.py compress --extension=.haml,.html --force
python manage.py migrate

python manage.py runserver 0.0.0.0:8001